import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import Header from "@/components/Header";
import StairTransition from "@/components/StairTransition";

export const metadata: Metadata = {
  title: "The Robot Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full h-full px-10 lg:px-40">
        <Header/>
        <StairTransition/>
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
